# Generated by Django 5.1.5 on 2025-02-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome do Produto"),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="Link")),
                (
                    "pricePrevious",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Preço Anterior",
                    ),
                ),
                (
                    "installment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Parcelamento",
                    ),
                ),
                (
                    "price",
                    models.FloatField(blank=True, null=True, verbose_name="Preço"),
                ),
                (
                    "shipping_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tipo de Entrega",
                    ),
                ),
                (
                    "free_shipping",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Frete Grátis",
                    ),
                ),
                (
                    "percentual_discount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Percentual de Desconto"
                    ),
                ),
                (
                    "image",
                    models.URLField(blank=True, null=True, verbose_name="Imagem"),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
    ]
