# Generated by Django 4.2.5 on 2025-02-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='entire_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preço Total'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricePrevious',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preço Anterior'),
        ),
    ]
